import { test, expect } from '@playwright/test';
import { VaultDashboardPage } from '../pages/vault-dashboard';

// These tests are arbitrary and hard-coded against the current state of the mocked dashboard. Would need to be adjusted for a dynamic dashboard.
test.describe('Transaction History', () => {
  let dashboard: VaultDashboardPage;

  test.beforeEach(async ({ page }) => {
    dashboard = new VaultDashboardPage(page);
    await dashboard.goto();
  });

  test('displays all 8 transactions', async () => {
    await expect(dashboard.getAllTransactionRows().first()).toBeVisible(); // wait before counting
    const count = await dashboard.getAllTransactionRows().count();
    expect(count).toBe(8); // Hard-coded check of 8 would be modified for a more dynamic history table.
  });

  // Would be better if this test recognized date chronological order somehow and checked against that.
  test('sort toggle changes transaction order', async () => {
    // Capture the first row's text before sorting so we have something to compare against
    const firstRowBefore = await dashboard.getAllTransactionRows().first().innerText();
    await dashboard.toggleSort();
    const firstRowAfter = await dashboard.getAllTransactionRows().first().innerText();
    expect(firstRowAfter).not.toBe(firstRowBefore);
  });

  test('toggling sort twice restores original order', async () => {
    const firstRowOriginal = await dashboard.getAllTransactionRows().first().innerText();
    await dashboard.toggleSort();
    await dashboard.toggleSort();
    const firstRowRestored = await dashboard.getAllTransactionRows().first().innerText();
    expect(firstRowRestored).toBe(firstRowOriginal);
  });

  test('transaction count preserved after sorting', async () => {
    await dashboard.toggleSort();
    const count = await dashboard.getAllTransactionRows().count();
    expect(count).toBe(8);
  });

  // Would need to expand this for other transaction states on a real dashboard.
  test('all transactions show Confirmed status', async () => {
    // Array of all known transaction IDs — iterated with for...of to keep assertions readable
    const txIds = ['tx-1', 'tx-2', 'tx-3', 'tx-4', 'tx-5', 'tx-6', 'tx-7', 'tx-8'];
    for (const txId of txIds) {
      await expect(dashboard.getTxStatus(txId)).toHaveText('Confirmed');
    }
  });
});

test.describe('Transaction Expanded Details', () => {
  let dashboard: VaultDashboardPage;

  test.beforeEach(async ({ page }) => {
    dashboard = new VaultDashboardPage(page);
    await dashboard.goto();
  });

  test('expanding a transaction reveals detail fields', async () => {
    await dashboard.expandTransaction('tx-8');
    // Grab all rendered text from the body as a single string for loose content checks. Could be made more precise.
    const expandedContent = await dashboard.page.locator('body').innerText();
    // toContain checks that the string includes the given substring anywhere within it
    expect(expandedContent).toContain('Full Address');
    expect(expandedContent).toContain('Transaction Hash');
    expect(expandedContent).toContain('Block Height');
    expect(expandedContent).toContain('Timestamp');
    expect(expandedContent).toContain('Fee (sats)');
  });

  // Close buttons are called in several tests, could be moved to the POM.
  test('expanded view has a Close button', async () => {
    await dashboard.expandTransaction('tx-8');
    const closeBtn = dashboard.page.getByTestId('tx-detail-close-tx-8');
    await expect(closeBtn).toBeVisible();
  });

  // Complex test generated by Claude that might benefit from clearer requirements, and some simplification.
  test('block heights increase chronologically', async () => {
    // Newer transactions should have higher block heights.
    await dashboard.expandTransaction('tx-8');
    const content = await dashboard.page.locator('body').innerText();
    // String.match() returns an array: index 0 is the full match, index 1+ are capture groups.
    // This capture group grabs the digit string on the line after "Block Height".
    const blockMatch = content.match(/Block Height\n([\d,]+)/);
    // parseInt with base 10 after stripping commas — converts "860,123" → 860123
    // The ternary (condition ? valueIfTrue : valueIfFalse) provides a safe fallback of 0
    // if the regex finds no match
    const olderBlock = blockMatch ? parseInt(blockMatch[1].replace(/,/g, '')) : 0;

    // Close the expanded panel before opening another transaction
    await dashboard.page.getByTestId('tx-detail-close-tx-8').click();
    await dashboard.page.waitForTimeout(300);

    await dashboard.expandTransaction('tx-3');
    const content2 = await dashboard.page.locator('body').innerText();
    const blockMatch2 = content2.match(/Block Height\n([\d,]+)/);
    const newerBlock = blockMatch2 ? parseInt(blockMatch2[1].replace(/,/g, '')) : 0;

    expect(newerBlock).toBeGreaterThan(olderBlock);
  });
});

test.describe('Transaction Data Integrity - Bugs', () => {
  let dashboard: VaultDashboardPage;

  test.beforeEach(async ({ page }) => {
    dashboard = new VaultDashboardPage(page);
    await dashboard.goto();
  });

  test('BUG: tx-1 has 0 confirmations but shows Confirmed status', async () => {
    // Status should be "Pending" or "Unconfirmed".
    const confirmations = await dashboard.getTxConfirmations('tx-1').innerText();
    const status = await dashboard.getTxStatus('tx-1').innerText();

    expect(confirmations).toBe('0');
    expect(status).not.toBe('Confirmed'); // Expected to FAIL
  });

  test('BUG: tx-5 fee (0.1 BTC) is 20x the send amount (0.005 BTC)', async () => {
    // Fee of ~$5,000 on a ~$250 send. Typical fees: 0.00001–0.0005 BTC.
    const fee = await dashboard.getTxFee('tx-5').innerText();
    // parseFloat converts a numeric string (e.g. "0.1") to a JavaScript number for comparison
    const feeValue = parseFloat(fee);
    expect(feeValue).toBeLessThan(0.001); // Expected to FAIL
  });

  test('BUG: tx-8 expanded timestamp does not match row date', async () => {
    await dashboard.expandTransaction('tx-8');

    const detailsPane = dashboard.page.getByTestId('transaction-detail-tx-8');

    await expect(detailsPane).toBeVisible();

    const expandedContent = await detailsPane.innerText();
    expect(expandedContent).toContain('Jan 10'); // Expected to FAIL if timestamp shows Jan 9. Bug, possibly around timezones.
  });

});
