import { test, expect } from '@playwright/test';

// Note: this file does not use VaultDashboardPage — these tests interact with the
// network layer directly via Playwright's response interception API.

/**
 * API and security observations based on network activity observed during
 * initial page load (browser console inspection of staging environment).
 *
 * Observed endpoints:
 *   GET /vaultApi/api/application/geo    → { isUnitedStates: true }
 *   GET /vaultApi/api/application/status → { minimumAppVersion, maintenanceMode, useElectrum, ... }
 *   GET /vaultApi/api/users/me           → 401 (no auth token)
 *
 * External services detected: LaunchDarkly (feature flags), Datadog (monitoring), Stripe (payments)
 */

// Tests generated by Claude, just to show examples of API checks. No real requirements here.
// Would want to refactor and simplify some of these based on clearer test cases.

test.describe('API Observations', () => {

  test('status endpoint returns valid app metadata', async ({ page }) => {
    // page.waitForResponse() registers a listener BEFORE navigation and returns a Promise.
    // The argument is an arrow function filter — Playwright calls it for every response
    // and resolves the Promise the first time the function returns true.
    // The listener must be set up before goto() so no responses are missed.
    const statusResponse = page.waitForResponse(
      resp => resp.url().includes('/api/application/status') && resp.status() === 200
    );
    await page.goto('https://app-stg.keys.casa/qa_hire_q1_2026');
    // Awaiting the Promise pauses execution here until the matching response arrives
    const response = await statusResponse;
    // Parse the response body as JSON — returns a plain JavaScript object
    const body = await response.json();

    // toHaveProperty checks that the parsed object contains the given key
    expect(body).toHaveProperty('minimumAppVersion');
    // Validate the value follows semver format: three digit groups separated by dots (e.g. "1.2.3")
    expect(body.minimumAppVersion).toMatch(/^\d+\.\d+\.\d+$/);
    expect(body).toHaveProperty('maintenanceMode');
    // typeof returns a runtime type string — confirms maintenanceMode is an actual boolean,
    // not a string "true"/"false" or a number
    expect(typeof body.maintenanceMode).toBe('boolean');
  });

  test('unauthenticated request to /users/me returns 401', async ({ page }) => {
    // Same pattern: register the listener before triggering navigation
    const authResponse = page.waitForResponse(
      resp => resp.url().includes('/api/users/me')
    );
    await page.goto('https://app-stg.keys.casa/qa_hire_q1_2026');
    const response = await authResponse;

    // 401 Unauthorized — confirms the endpoint enforces authentication
    // and does not accidentally serve data to unauthenticated requests
    expect(response.status()).toBe(401);
  });
});

test.describe('Security Observations', () => {

  test('page loads over HTTPS', async ({ page }) => {
    await page.goto('https://app-stg.keys.casa/qa_hire_q1_2026');
    // page.url() returns the final URL after any redirects.
    // The regex /^https:\/\// checks that it begins with "https://" —
    // \/ escapes the forward slashes which are special characters inside regex literals
    expect(page.url()).toMatch(/^https:\/\//);
  });

  test('no private keys or xpubs exposed in page source', async ({ page }) => {
    // Casa's API documentation explicitly states xpubs are not revealed for privacy.
    // (Source: https://casa.io/api — "The Casa API does not reveal extended public keys
    //  (xpubs) for privacy reasons.")

    // This could be refactored to more directly listen to network payloads, but is fine for now.

    // Promise.all() runs both promises concurrently and resolves only when BOTH have settled.
    // This ensures we don't scrape the DOM before the vault data has loaded —
    // without it, the assertions would pass trivially because the data hasn't arrived yet.
    await Promise.all([
      page.waitForResponse(resp => resp.url().includes('/api/application/status') && resp.status() === 200),
      page.goto('https://app-stg.keys.casa/qa_hire_q1_2026')
    ]);

    // page.content() returns the full HTML source of the current page as a string —
    // includes both static markup and anything React has rendered into the DOM
    const content = await page.content();

    // xprv / xpub are the prefixes for Bitcoin extended private and public keys (BIP 32).
    // [0-9A-Za-z]{107} matches the 107 Base58 characters that follow the prefix in a standard
    // extended key — making this a format-aware check rather than a naive keyword search.
    expect(content).not.toMatch(/xprv[0-9A-Za-z]{107}/);
    expect(content).not.toMatch(/xpub[0-9A-Za-z]{107}/);
  });


  // TODO: Add a check for sensitive data in console errors, a common leak vector. Terms: 'private key', 'mnemonic', 'xprv'
  // TODO: Verify Content-Security-Policy headers restrict script sources
  // TODO: Verify Strict-Transport-Security header is present
  // TODO: Audit LaunchDarkly client key exposure (visible in network stream URL) —
  //       client-side LD keys are expected to be public, but worth confirming
  //       no server-side SDK key is accidentally exposed
});
